### ISSUE TITLE
Regarding the notify-new-users-from-import.php

### ISSUE THREAD

**Issue by thewpguy** [skyverge/wc-plugins-snippets#4]
This is great and really appreciated.
Is there any way to delay the notification being sent to new users by 5 mins as we have a follow up email that is sent about 5 mins after members are manually added and that would make the email flow a bit closer. 

Warm regards,
Tony

**Comment by bekarice** [comment]
hey Tony! I'm afraid I can't really recommend that tact -- you'd need to set up a single scheduled event for every membership 5 minutes into the future during import, and WP cron is notoriously unreliable in terms of sending on time as well as sending an action only once (as it can fire multiple times) -- not to mention that this could slow down import processing at scale.

Since you're using Follow Ups, leveraging the Action Scheduler library in that plugin may be a better route, as you could consider creating an event that loops through an array of user membership IDs to send this email out 5 min later. It's not something we have sample code ready for, but that would be the path I'd recommend following 😄

**Comment by thewpguy** [comment]
Hi Beka, first and foremost thanks for the fastest response I've ever had on a plugin question, greatly appreciated.
I had set the wp cron to a 10min schedule which was part of the issue. Once returned it to the default the gap closed to about 1 -2 minutes which worked a lot better for the user experience so looks like a win. At least I know now that you are a great help with any future questions. Have a great week-end.
